create table COCKTAIL_SHOPPING_LIST (
  COCKTAIL_ID UUID REFERENCES  COCKTAIL(ID) ON DELETE CASCADE,
  SHOPPING_LIST_ID UUID REFERENCES SHOPPING_LIST(ID) ON DELETE CASCADE,
  PRIMARY KEY (COCKTAIL_ID, SHOPPING_LIST_ID)
);